version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint:
    docker:
      - image: cimg/node:18.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run linter
          command: yarn lint

workflows:
  ci:
    jobs:
      - lint
      - node/test:
          version: '18.0'
          pkg-manager: yarn